worker_processes  1;

pid /data/data/com.termux/files/home/repos/quillqr/logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include /data/data/com.termux/files/usr/etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /data/data/com.termux/files/home/repos/quillqr/logs/nginx-access.log;
    error_log  /data/data/com.termux/files/home/repos/quillqr/logs/nginx-error.log;

    sendfile on;

    server {
        listen 127.0.0.1:8080;
        server_name localhost;

        client_max_body_size 256k;

        location /static/ {
            alias /data/data/com.termux/files/home/repos/quillqr/static/;
        }

		location / {
			proxy_pass http://127.0.0.1:8000;

			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-Host $host;
			proxy_set_header X-Forwarded-Port $server_port;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
    }
}
